version: '3.4'

services:
  investmentchat.web:
    image: ${DOCKER_REGISTRY-}investmentchatweb
    build:
      context: .
      dockerfile: InvestmentChat.Web/Dockerfile
    depends_on:
        - investmentchat.api
        - investmentchat.identity


  investmentchat.api:
    image: ${DOCKER_REGISTRY-}investmentchatapi
    build:
      context: .
      dockerfile: InvestmentChat.Api/Dockerfile
    depends_on:
        - rabbitmq
        - investmentchat.bot

  investmentchat.identity:
    image: ${DOCKER_REGISTRY-}investmentchatidentity
    build:
      context: .
      dockerfile: InvestmentChat.Identity/Dockerfile
    depends_on: 
        - mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: InvestmentChat.rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"

  investmentchat.bot:
    image: ${DOCKER_REGISTRY-}investmentchatbot
    build:
      context: .
      dockerfile: InvestmentChat.Bot/Dockerfile
    depends_on:
        - rabbitmq

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Insecure!12345